
spring:
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: org.mariadb.jdbc.Driver
server:
  port: 52012
